### ISSUE TITLE
Add flexbox for layouts

### ISSUE THREAD

**Issue by bdielman** [the-refinery/baseline#11]
For version 2.0 we should move to flexbox. We'll be using feature detection with Modernizr to deliver the current layout styles for less capable browsers.

**Comment by joefiorini** [comment]
:+1: I've been looking to use Flexbox myself, and am hoping to move us to a baseline architecture soon (we're on Less so can't use it by itself).

**Comment by bdielman** [comment]
Hope to get this implemented soon.

**Comment by bdielman** [comment]
Closing this issue as layouts are handled fine by the current grid. Smaller components are using flexbox with fall-backs for older browsers if need be.
